name = "QCkits"
version = "0.1.0"
license = "license"
author = "St Maxwell"
maintainer = "st_maxwell@outlook.com"
copyright = "Copyright 2021, St Maxwell"
[build]
#auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
